output "aws_rds_cluster_main_endpoint" {
  value = aws_rds_cluster.main.endpoint
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}
